/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package UI;

import Clases.Player;
import Clases.Sistema;
import Clases.Jockey;
import Estructuras.Lista;
import Clases.HorseRace;
import Estructuras.Pila;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Date;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;



/**
 *
 * @author isaac
 */
public class MenuRace extends javax.swing.JFrame {
    

    public  static Sistema sistema;
  public static  boolean begin;
  public static ThreadRace t;

    /**
     * Creates new form Login
     */
    public MenuRace(Sistema sistema) {
        initComponents();
        this.setTitle("Sport HOlding");
        this.closeWindow();
        this.sistema = sistema;
        this.jLabelMount.setText("Money available " + String.valueOf(sistema.getActiveUser().getMount()));
        this.t = new ThreadRace(sistema);
        this.setVisible(true);
       // initTable();
       initTable(sistema.getHorseRace().getJockeys());
     //msg();
     //sistema.sleepThread(2500);
     //racing();
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/Logo.png")));
    }


    public void closeWindow() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmClose();
                }
            });
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void confirmClose() {
        int seleccion = JOptionPane.showOptionDialog(
                this,
                "Do you want to exit?",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                new Object[]{"Exit", "Sign Out", "Cancel"}, // null para YES, NO y CANCEL
                "opcion 1");

        if (seleccion == 0) {
            System.out.println("0");
            sistema.saveUser();
            System.out.println("Saving sistem");
            System.exit(0);
        }
        if (seleccion == 1) {
            System.out.println("1");
            Login login = new Login();
            sistema.saveUser();
            System.out.println("Saving sistem");
            dispose();
        }
        if (seleccion == 2) {
            System.out.println("seleccionada opcion 2");
        }
    }


     public static void initTable(Lista<Jockey> l) {
     DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        Jockey[] row = new Jockey[6];
        String[] row2 = new String[6];
        String[] row3 = new String[6];
        int i=0;
        for (Jockey j: l) {
            j.calculateProbability(l.size());
            row[i]=j;
            row2[i]=j.histString();
            row3[i]=j.getProbability()+"%";
          
            i++;
        }
      modelo.addRow(row);
      modelo.addRow(row2);
      modelo.addRow(row3);

   }

  
   public void tempo(){
    for(int i=10; i>=0;i--){
        jLabel2.setText(String.valueOf(i));
       
       // jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 170, 80));
        sistema.sleepThread(500);

        this.setVisible(true);
        //initComponents();
        }
   }

public  static void racing(){
    begin=true;
    sistema.getHorseRace().playRace(sistema.getHorseRace().getJockeys().elemInd(0));
    initTable(sistema.getHorseRace().getJockeys());
    begin=false;
}
    

   

    

    

   

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelMount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Carrera");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 170, 80));

        jButton3.setBackground(new java.awt.Color(214, 169, 108));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Start");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 120, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jockey 1", "Jockey 2", "Jockey 3", "Jockey 4", "Jockey 5", "Jockey 6"
               
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }

           
        });


           
     
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 840, 250));

        jLabelMount.setText("jLabel3");
        jPanel2.add(jLabelMount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 290, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
     
          //  sistema.getHorseRace().playRace(sistema.getHorseRace().getJockeys().elemInd(0));
    }// </editor-fold>//GEN-END:initComponents
static int j=0;

public static void msg(String h){
   JOptionPane pane = new JOptionPane("Anuncio");
    pane.showMessageDialog(null, h);
   // pane.contains(p)

}
   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_jButton3ActionPerformed
     Thread th = new Thread(t);
       th.run();
     
       
    }//GEN-LAST:event_jButton3ActionPerformed

  private void jTable1MouseMoved(java.awt.event.MouseEvent evt){
      tempo();
  }

    /* public void run(){
     new Menu().setVisible(true);
    }*/

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       if(begin==false){
        int index = this.jTable1.getSelectedColumn();
        TableModel model = jTable1.getModel();
    
        if (model.getValueAt(1, index) !=null) {
            //menuBet bet = new menuBet(sistema, index);
            menuBetJockey m = new menuBetJockey(sistema,index);

           // initTable(sistema.getHorseRace().getJockeys());
            System.out.println("Este es el usuario que llega "+sistema.getActiveUser());
        }
        this.jLabelMount.setText("Money available " + String.valueOf(sistema.getActiveUser().getMount()));
    }
    }//GEN-LAST:event_jTable1MouseClicked
    public void setNimbusLookAndFeel() {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMount;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}


